### PR TITLE
CKBotSim fix

### PR DESCRIPTION
**Pull request by amptrofa**
Fixes CKBotSim so it will work now, and without the changed line endings. The only way I could get that to work is by homogenizing the line endings across the whole repo, but the other files are JUST line ending fixes.

### CODE REVIEW

**Comment by cfinucane** [comment]
Hey, sorry, I didn't see this until just now.

Wow, I didn't realize we had quite so much CRLF in the repository :(  That said, I'm sorry to say it but I think we need to wait on the repo-wide homogenization until a couple of large upcoming refactor branches are merged back in.  

Could you make this pull request isolated to just CKBot stuff?  (You imply that that didn't work, for some reason, but I'm not sure why.)

**Comment by amptrofa** [comment]
I realized after the fact that I should have only git added the one file
before committing.

When I tried to do the rollback, I wound up wrestling with git trying to
figure out what was going on for something like 90 minutes. I'd really
rather not do that again, maybe you could give me a hand with the
mechanics of that process? We could take care of it after the meeting on
Friday (easiest) or just about any time tomorrow if you'd rather.

I realize I'm very git-challenged, sorry about that.

**Comment by amptrofa** [comment]
Fixed.

**Comment by cfinucane** [comment]
Tabs are now normalized to 4spaces. Thanks.

**Pull request merged**
